import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full text-gray-50 bg-gray-800">
      <body className={`${inter.className} antialiased font-sans h-full`}>
        <div className="flex flex-col h-full max-w-md mx-auto">
          <div className="mt-4 px-2">
            <Link href="/" className="tracking-tighter font-bold text-5xl">
              Stocks
            </Link>
          </div>

          <div className="grow mt-10 md:mt-12 flex flex-col flex-1">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
